server:
  port: 8888
  servlet:
    context-path: /chansey
spring:
  application:
    name: fuxing-tools
  datasource:
    url: jdbc:mysql://10.101.12.44:3306/fuxing-tools?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: chinadep@123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect